server:
  port: 8080

spring:
  jpa:
    show-sql: true
  datasources:
    tenant1:
      url: jdbc:postgresql://localhost:5432/tenant1
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    tenant2:
      url: jdbc:postgresql://localhost:5432/tenant2
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver